#!/usr/bin/env python

# $Id: dls-get-se-byAPI,v 1.1 2006/02/16 16:16:24 slacapra Exp $ 

import socket
import getopt
import sys
from DLS_client import *

if __name__ == "__main__":
    client=DLS_client()
    sys.exit(client.connect())
