#!/usr/bin/python

# $Id: dls-get-se,v 1.3 2006/01/06 17:46:30 afanfani Exp $ 

import socket
import getopt
import sys
from DLS_client import *

if __name__ == "__main__":
    client=DLS_client()
    sys.exit(client.connect())
