#!/usr/bin/env python

#
# $Id: dls-rename,v 1.2 2007/02/05 15:39:56 delgadop Exp $
#
# DLS Client. $Name:  $.
# Antonio Delgado Peris. CIEMAT. CMS.
# 

#########################################
# Imports 
#########################################
import dlsApi
DLS_VERB_HIGH = dlsApi.DLS_VERB_HIGH
DLS_VERB_WARN = dlsApi.DLS_VERB_WARN
from dlsDataObjects import DlsFileBlock
import dlsClient
from dlsCommandsCommon import *
from os import environ
import sys
import commands
import getopt


######################### FUNCTIONS ########################

def usage():
   """
    Provides usage information
   """
   print "Usage: dls-rename [-v, -t, -p, -e, -i] <old_fileblock> <new_fileblock>"
   print "       dls-rename [-v, -t, -p, -e, -i] -f <listing_file>"
   print "       dls-rename -u"
   print "       dls-rename -h"

def options():
   """
    Provides some information regarding the available options
   """
   print """Options summary:
   -h, --help
   -u, --usage
   -v, --verbose <verb_level>
   -t, --transaction
   -e, --endpoint <endpoint>
   -i, --interface-type <iface_type>
   -f, --from-file <filename>
   -p, --create-parent
   """
def example():
  """
   Provides with an example of correct use of the script
  """
  print """
  """

def help():
   """
    Provides some help information
   """
   print """Renames a FileBlock in the DLS server: from <old_fileblock> to
<new_fileblock>. 

If the new FileBlock already exists, it is removed before the renaming takes
place. 


Specific notes for DBS back-end (DLS_TYPE_DBS):

  At this point, this command does not support DLS's with DBS back-end.

  For the DBS back-end implementation, DLS interface cannot create or update
  FileBlocks (they are managed by other means), and thus they cannot
  be renamed either.


Specific notes for LFC back-end (DLS_TYPE_LFC):
 
  LFC implements a hierarchical FileBlock namespace. The arguments of this
  command can also be FileBlock directories. If the destination directory exists, then
  it must be empty must be empty (so that it can be removed).
  
  The server endpoint should be of the form: "hname[:port][/path/to/DLS]",
  where a default port is used if not specified, and the path to DLS is
  required. The server endpoint is retrieved from (in orden of precedence):
     - specified value for --endpoint option 
     - DLS_ENDPOINT environmental variable


Options:
  
If "-p" is specified, then the parent directories of the new FileBlock are checked
for existence, and created if non existing. Be aware that using this option for new
FileBlocks in directories already existing is unnecesary and may slow down the
operation slightly.

The "-f" option can be used to retrieve multiple old and new FileBlock names
from a file. This may be quite faster than invoking the command several times.
The file must contain one line per pair of old/new FileBlock names, separated
by whitespaces. In this case, the "-p" option has the same meaning as before
and affects all FileBlocks in <listfile>.

The "-t" option indicates if transactions should be used. In that case, any
error in an operation causes a stop (no more renamings) and a rollback of
the previous operations. Otherwise (no transactions), after a failure in one
renaming, the tool tries to go on with the rest.

 NOTE: It is not recommended to maintain a transaction for too long (~10 seconds).
 Thus, it is suggested not to include too many FileBlocks in a <listfile> if
 transactions are to be used. For a larger number of FileBlocks, please split
 them into several invocations of the command.

The "-e" option can be used to set the DLS endpoint to use. 

The "-i" option specifies the type of interface that should be used (which
depends on the DLS backend to access). If not specified, the interface type
is retrieved from:
    - DLS_TYPE environmental variable
If the interface type cannot be retrieved in any of these ways, the command fails.
Currently accepted values are:
    - DLS_TYPE_LFC  =>  DlsLfcApi class (complete API with LFC back-end)
    - DLS_TYPE_MYSQL => DlsMySQLApi  class (complete API with MySQL proto back-end) 

The "-v" option sets the verbosity level for the command. Accepted values are:
  -v 0 ==> print nothing else than error messages
  -v 1 ==> print also warning messages (default)
  -v 2 ==> print extra debug information

If "-u" is specified, usage information is displayed.

If "-h" is specified, help information is displayed.
   """
   options()
   usage()



def rename(iface, lineList, createParent, trans, verbose):
   """
    Tries to rename FileBlocks, as specified in each of the lines in lineList.
    These lines are strings containing the old and the new names of the
    FileBlocks to rename.

    The format of a line is then:
    <old_lfn> <new_lfn>

    All elements separated by whitespaces.

    Throws DlsLfcApiError if there is a problem in the DLS operation, unless
    trans is set to True.
   """

   if(trans):
      iface.startTrans()
   else:
      iface.startSession()

   for line in lineList:

      # Split
      line = (line.strip()).split()
      if((not line) or (len(line)<2)):
         continue
         
      # Get LFNs
      oldLfn = line.pop(0)
      newLfn = line.pop(0)

      # Do the rename
      try:
         if(verbose >= 2):
            print "--DlsApi.rename(\"%s\",\"%s\")" % (oldLfn, newLfn)
         iface.renameFileBlock(oldLfn, newLfn, createParent=createParent,trans=False,session=False)
      except dlsApi.DlsApiError, inst:         
         if(trans):
             iface.abortTrans()
             inst.msg += ". Transaction operations rolled back"
             raise inst
         else: 
           continue

   if(trans):
      iface.endTrans()
   else:
      iface.endSession()

            

###################### MAIN FUNCTION ########################

def main(pArgs):
   """
    Performes the main task of the script (invoked directly).
    For information on its functionality, please call the help function.
   """

 # Options and args... 
 
   longoptions=["help", "usage", "create-parent", "transaction", "endpoint", "interface-type", "verbose","from-file"]
   try:
      optlist, args = getopt.getopt(pArgs, 'hupte:i:v:f:', longoptions)
   except getopt.GetoptError, inst:
      sys.stderr.write("Bad usage: "+str(inst)+'\n')
      usage()
      sys.exit(OPT_ERROR)

   err=0
   createParent = False 
   trans = False
   admitted_verb_values = [0, 1, 2]
   verbose = 1
   endpoint = None
   iface_type = None
   admitted_iface_types = ["DLS_TYPE_LFC", "DLS_TYPE_MYSQL"]
   fromFile = False
   fname=""
   for opt, val in optlist:
       if opt in ("-h", "--help"):
           help()
           return OPT_ERROR

       elif opt in ("-u", "--usage"):
           usage()
           return OPT_ERROR
           
       elif opt in ("-p", "--create-parent"):
           createParent = True
           
       elif opt in ("-t", "--transaction"):
           trans = True

       elif opt in ("-e","--endpoint"):
           endpoint = val

       elif opt in ("-i", "--interface-type"):
           iface_type = val

       elif opt in ("-v", "--verbose"):
           try: 
             val = int(val)
           except ValueError, inst:
             sys.stderr.write("Unsupported verbosity value: " + val + "\n")
             return OPT_ERROR
           if (not (val in admitted_verb_values)):
              sys.stderr.write("Unsupported verbosity value: " + val + "\n")
              return OPT_ERROR             
           verbose = val

       elif opt in ("-f","--from-file"):
           fromFile = True
           fname = val
           
  
   # Check the interface type (from options or environ)
   if (not iface_type):
      iface_type = environ.get("DLS_TYPE")
   val = iface_type
   if (not (val in admitted_iface_types)):
      msg = "Unsupported interface type: "+str(val)+"\nSupported values: "+str(admitted_iface_types)
      sys.stderr.write(msg+'\n')
      return TYPE_ERROR
   if(val == "DLS_TYPE_LFC"):
      iface_type = dlsClient.DLS_TYPE_LFC
   if(val == "DLS_TYPE_MYSQL"):
      iface_type = dlsClient.DLS_TYPE_MYSQL


 # Build the arguments

   # From file
   if(fromFile):
      try:
         file=open(fname, 'r')
      except IOError, inst:
         msg="The file "+fname+" could not be opened: "+str(inst)+"\n"
         sys.stderr.write(msg)
         return FILE_ERROR
      lineList=file.readlines()
      
   # From command line options
   else:
      if(len(args)<2):
         sys.stderr.write("Not enough input arguments\n")
         usage()
         return(OPT_ERROR)

      line=""
      for token in args:
         line += token +" "
      lineList = [line]


 # Create the interface binding
   try:
      iface = dlsClient.getDlsApi(iface_type, endpoint)
      if(verbose == 2):
         iface.setVerbosity(dlsApi.DLS_VERB_HIGH)
      else:
         if(verbose == 0):
            iface.setVerbosity(dlsApi.DLS_VERB_NONE)
         else:
            if(verbose == 1):
               iface.setVerbosity(dlsApi.DLS_VERB_WARN)
   except dlsApi.DlsApiError, inst:
      if(inst.rc):  err = inst.rc 
      else:         err = GENERIC_ERROR
      msg = "Error when binding the DLS interface: " + str(inst)
      sys.stderr.write(msg+"\n")
      return err

      
   try:
     rename(iface, lineList, createParent, trans, verbose)
   except dlsApi.DlsApiError, inst:         
      if(inst.rc):  err = inst.rc 
      else:           err = GENERIC_ERROR
      msg = "Error in the FileBlock(s) renaming: %s." % str(inst)
      sys.stderr.write(msg+'\n')

 # Finally, return error code
   return err



######################### SCRIPT ###########################

if __name__ == "__main__":
  sys.exit(main(sys.argv[1:]))
