#!/usr/bin/env python

#
# $Id: dls-get-fileblock,v 1.11 2007/03/16 12:39:51 delgadop Exp $
#
# DLS Client. $Name:  $.
# Antonio Delgado Peris. CIEMAT. CMS.
# 

#########################################
# Imports 
#########################################
import dlsApi
DLS_VERB_HIGH = dlsApi.DLS_VERB_HIGH
DLS_VERB_WARN = dlsApi.DLS_VERB_WARN
from dlsDataObjects import DlsLocation, DlsFileBlock, DlsEntry
import dlsClient
from dlsCommandsCommon import *
import time
from os import environ
import sys
import commands
import getopt


################## GLOBAL CONSTANTS ########################
THIS_YEAR = time.localtime()[0]


######################### FUNCTIONS ########################

def usage():
   """
    Provides usage information
   """
   print "Usage: dls-get-fileblock [-v, -e, -i, --dbs-conf] <location>"
   print "       dls-get-fileblock [-v, -e, -i, --dbs-conf] -f <listing_file>"
   print "       dls-get-fileblock -u"
   print "       dls-get-fileblock -h"


def options():
   """
    Provides some information regarding the available options
   """
   print """Options summary:
   -h, --help
   -u, --usage
   -v, --verbose <verb_level>
   -e, --endpoint <endpoint>
   -i, --interface-type <iface_type>
   -f, --from-file <filename>
       --dbs-conf <conf_file>
   """
def example():
  """
   Provides with an example of correct use of the script
  """
  print """
  """

def help():
   """
    Provides some help information
   """
   print """This script will print the FileBlock entries that are associated with the
specified location (i.e., there is a copy of that FileBlock in that location (SE)).


Specific notes for DBS back-end (DLS_TYPE_DBS):

  The argument of this command will be taken as a Storage Element name pattern.
  All the Fileblocks associated with the matching SEs will be returned.

  The server endpoint is got from a string in the URL form, usually:
    "http[s]://hname[:port]/path/to/DLS".
  This endpoint is retrieved from several sources (in order of precedence):   
     - specified value for --endpoint option 
     - DLS_ENDPOINT environmental variable
     - specified URL in the configuration file (see --dbs-conf)

  Apart from DBS endpoint, other configuration options may be specified for
  the underlying DBS interface (e.g. "level" for DBS logging level) in a
  configuration file. The name of this file can be indicated with,
  in this order:
     - specified value for --dbs-conf option
     - DBS_CLIENT_CONFIG environmental variable


Specific notes for LFC back-end (DLS_TYPE_LFC):

  The argument of this command is the a Storage Element name.

   NOTE: Depending on the implementation, this method may be a very expensive
   operation and affect DLS response, so use it only with care!!

  The server endpoint should be of the form: "hname[:port][/path/to/DLS]",
  where a default port is used if not specified, and the path to DLS is
  required. The server endpoint is retrieved from (in orden of precedence):
     - specified value for --endpoint option 
     - DLS_ENDPOINT environmental variable


Options:

The "-f" option can be used to retrieve locations from a file rather than from the
given arguments. The file must contain one line per SE to be listed.

The "-e" option can be used to set the DLS endpoint to use. 

The "-i" option specifies the type of interface that should be used (which
depends on the DLS backend to access). If not specified, the interface type
is retrieved from:
    - DLS_TYPE environmental variable
If the interface type cannot be retrieved in any of these ways, the command fails.
Currently accepted values are:
    - DLS_TYPE_DBS =>   DLS_TYPE_DBS class (complete API with DBS back-end)
    - DLS_TYPE_LFC  =>  DlsLfcApi class (complete API with LFC back-end)
    - DLS_TYPE_MYSQL =>  DlsMySQLApi  class (complete API with MySQL proto back-end) 

The "-v" option sets the verbosity level for the command. Accepted values are:
  -v 0 ==> print nothing else than error messages
  -v 1 ==> print also warning messages (default)
  -v 2 ==> print extra debug information

If "-u" is specified, usage information is displayed.

If "-h" is specified, help information is displayed.
   """
   options()
   usage()



def showFileBlocks(iface, lineList, verbose):
   """
    Prints the FileBlocks that are stored in the specified location.
    lineList is a list of strings, each holding a location host. 
    
    Throws DlsLfcApiError if there is a problem in the DLS operation.
   """

   locList = []
   for line in lineList:

      # Split
      line = (line.strip()).split()
      if(not line):
         continue

      # Get location
      host = line.pop(0)

      # Store all the FileBlocks 
      locList.append(host)

   if(verbose >= 2):
      print "--DlsApi.getFileBlocks(",
      for i in locList: print i, ";",
      print ")"

   # Get the FileBlocks (and let the caller deal with the exception...)
   entryList = iface.getFileBlocks(locList, session = True)



   # Extract the locations returned
   locsDict = {}
   for entry in entryList:
      for loc in entry.locations:
         if(locsDict.has_key(loc.host)):
            locsDict[loc.host].append(entry.fileBlock.name)
         else:
            locsDict[loc.host] = [entry.fileBlock.name]
   
   # Do we print the header? Always, unless we asked for 1, and without patterns.
   with_heathers = (len(locList) > 1) or (len(locsDict.keys()) > 1) or (locsDict.keys() != locList)
   
   # Print the list   
   for loc in locsDict.keys():
      if(with_heathers):
         print "  Location: " + loc 
      for block in locsDict[loc]:
         print block

            

###################### MAIN FUNCTION ########################

def main(pArgs):
   """
    Performes the main task of the script (invoked directly).
    For information on its functionality, please call the help function.
   """

 # Options and args... 
 
   longoptions=["help", "usage", "endpoint", "interface-type", "verbose","from-file", "dbs-conf="]
   try:
      optlist, args = getopt.getopt(pArgs, 'hue:i:v:f:', longoptions)
   except getopt.GetoptError, inst:
      sys.stderr.write("Bad usage: "+str(inst)+'\n')
      usage()
      sys.exit(OPT_ERROR)

   err=0
   dbsConf = None
   admitted_verb_values = [0, 1, 2]
   verbose = 1
   endpoint = None
   iface_type = None
   admitted_iface_types = ["DLS_TYPE_LFC", "DLS_TYPE_DBS", "DLS_TYPE_MYSQL"]
   fromFile = False
   fname=""
   for opt, val in optlist:
       if opt in ("-h", "--help"):
           help()
           return OPT_ERROR

       elif opt in ("-u", "--usage"):
           usage()
           return OPT_ERROR
           
       elif opt in ("", "--dbs-conf"):
           dbsConf = val

       elif opt in ("-e","--endpoint"):
           endpoint = val

       elif opt in ("-i", "--interface-type"):
           iface_type = val

       elif opt in ("-v", "--verbose"):
           try: 
             val = int(val)
           except ValueError, inst:
             sys.stderr.write("Unsupported verbosity value: " + val + "\n")
             return OPT_ERROR
           if (not (val in admitted_verb_values)):
              sys.stderr.write("Unsupported verbosity value: " + val + "\n")
              return OPT_ERROR             
           verbose = val

       elif opt in ("-f","--from-file"):
           fromFile = True
           fname = val

   # Check the interface type (from options or environ)
   if (not iface_type):
      iface_type = environ.get("DLS_TYPE")
   val = iface_type
   if (not (val in admitted_iface_types)):
      msg = "Unsupported interface type: "+str(val)+"\nSupported values: "+str(admitted_iface_types)
      sys.stderr.write(msg+'\n')
      return TYPE_ERROR
   if(val == "DLS_TYPE_DBS"):
      iface_type = dlsClient.DLS_TYPE_DBS
   if(val == "DLS_TYPE_LFC"):
      iface_type = dlsClient.DLS_TYPE_LFC
   if(val == "DLS_TYPE_MYSQL"):
      iface_type = dlsClient.DLS_TYPE_MYSQL



 # Build the arguments

   # From file
   if(fromFile):
      try:
         file=open(fname, 'r')
      except IOError, inst:
         msg="The file "+fname+" could not be opened: "+str(inst)+"\n"
         sys.stderr.write(msg)
         return FILE_ERROR
      lineList=file.readlines()
      
   # From command line options
   else:
      if(len(args)<1):
         sys.stderr.write("Not enough input arguments\n")
         usage()
         return(OPT_ERROR)

      line=""
      for token in args:
         line += token +" "
      lineList = [line]

 # Create the interface binding
   try:
      iface = dlsClient.getDlsApi(iface_type, endpoint, dbs_client_config = dbsConf)
      if(verbose == 2):
         iface.setVerbosity(dlsApi.DLS_VERB_HIGH)
      else:
         if(verbose == 0):
            iface.setVerbosity(dlsApi.DLS_VERB_NONE)
         else:
            if(verbose == 1):
               iface.setVerbosity(dlsApi.DLS_VERB_WARN)
   except dlsApi.DlsApiError, inst:
      if(inst.rc):  err = inst.rc 
      else:           err = GENERIC_ERROR
      msg = "Error when binding the DLS interface: " + str(inst)
      sys.stderr.write(msg+"\n")
      return err

   
 # Do the query (under session)
   try:
     showFileBlocks(iface, lineList, verbose)
   except dlsApi.DlsApiError, inst:         
      if(inst.rc):  err = inst.rc 
      else:           err = GENERIC_ERROR
      msg = "Error in the DLS query: %s." % str(inst)
      sys.stderr.write(msg+'\n')

 # Finally, return error code
   return err



######################### SCRIPT ###########################

if __name__ == "__main__":
  sys.exit(main(sys.argv[1:]))
